/// Flutter icons WeatherApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WeatherApp
///      fonts:
///       - asset: fonts/WeatherApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class WeatherApp {
  WeatherApp._();

  static const _kFontFam = 'WeatherApp';
  static const String _kFontPkg = "icons";

  static const IconData gauge = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_wind_7745 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData humidity = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
